// RETRIEVE ALL EXPENSES OR EXPANSES BY MONTH
export const FETCHING_EXPENSE = "FETCHING_EXPENSE";

// RETRIEVE EXPENSE BY ID
export const FETCH_EXPENSE_BY_ID = "FETCH_EXPENSE_BY_ID";

// CREATE EXPENSE
export const SAVE_EXPENSE = "SAVE_EXPENSE";

// UPDATE EXPENSES
export const EXPENSE_UPDATED = "EXPENSE_UPDATED";
export const UPDATE_FAILED = "UPDATE_FAILED";

// DELETE EXPENSE
export const DELETE_EXPENSE = "DELETE_EXPENSE";

// FETCH STATE
export const FETCHED_SUCCESS = "FETCHED_SUCCESS";
export const FETCHED_FAILED = "FETCHED_FAILED";